config/routes.rb
Rails.application.routes.draw do

  get '/cars/:id/rent' => 'cars#rent', as: 'rent'
  devise_for :users
  root :to => 'cars#index'
  resources :cars
  resources :users

end

app/models/car.rb
class Car < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :mini => "40x40" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  	validates :plate, :presence => true
  	validates :brand, :presence => true
  	validates :year, :presence => true
  	validates :capacity, :presence => true
  	validates :door, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :presence => true
  validates :lastname, :presence => true
  validates :identification, :presence => true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :mini => "40x40" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def fullname
  	return name + ' ' + lastname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	protected
	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) do |u|
	    u.permit(:name, :lastname, :address, :phone, :cellphone, :born_date, :identification, :avatar, :email, :password, :password_confirmation)
	  end
	  devise_parameter_sanitizer.for(:account_update) do |u|
	    u.permit(:name, :lastname, :address, :phone, :cellphone, :born_date, :identification, :avatar, :email, :password, :password_confirmation, :current_password)
	  end
	end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_filter :get_users
  before_action :set_car, only: [:show, :edit, :update, :destroy, :rent]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  def rent
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:plate, :mileage, :capacity, :brand, :year, :color, :motor, :description, :gasoline, :transmision, :trunk, :door, :avatar)
    end

    private
    def get_users
      @users = User.all.map {|user| [user.fullname, user.id]}
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastname, :address, :phone, :cellphone, :born_date, :identification, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flass_class(type)
		case type
			when :success then "success"
			when :error then "warning"
			when :alert then "warning"
			when :notice then ""
			else "info"
		end
	end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <fieldset class="small-6 columns">
      <h3>Basic Information</h3>

      <div class="field">
        <%= f.label :avatar %><br />
        <%= f.file_field :avatar %>
      </div>

      <div class="field">
        <%= f.label :plate %><br>
        <%= f.text_field :plate %>
      </div>

      <div class="field">
        <%= f.label :brand %><br>
        <%= f.text_field :brand %>
      </div>

      <div class="field">
        <%= f.label :year %><br>
        <%= f.number_field :year %>
      </div>

      <div class="field">
        <%= f.label :color %><br>
        <%= f.text_field :color %>
      </div>

      <div class="field">
        <%= f.label :capacity %><br>
        <%= f.number_field :capacity %>
      </div>

      <div class="field">
        <%= f.label :trunk %><br>
        <%= f.check_box :trunk %>
      </div>

      <div class="field">
        <%= f.label :door %><br>
        <%= f.number_field :door %>
      </div>
    </fieldset>

    <fieldset class="small-5 columns">
      <h3>Additional Information</h3>

      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>

      <div class="field">
        <%= f.label :mileage %><br>
        <%= f.text_field :mileage %>
      </div>

      <div class="field">
        <%= f.label :motor %><br>
        <%= f.text_field :motor %>
      </div>

      <div class="field">
        <%= f.label :gasoline %><br>
        <%= f.text_field :gasoline %>
      </div>

      <div class="field">
        <%= f.label :transmision %><br>
        <%= f.check_box :transmision %>
      </div>
    </fieldset>
  </div>

  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1 class="text-center">Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car, class: 'button' %>

app/views/cars/index.html.erb
<section class="content">
  <h1 class="text-center">Cars <% if user_signed_in? %> <span><%= link_to 'New', new_car_path %></span> <% end %></h1>

  <ul class="row">
    <% @cars.each do |car| %>
      <li class="small-4 columns">
        <article class="documents row">
          <div class=" small-12 columns"><%= image_tag car.avatar.url(:medium) %></div>
           <hgroup class="text-center small-12 columns">
             <h5><%= car.brand %></h5>
             <h6><b>Year: </b><%= car.year %></h6>
           </hgroup>

          <div class="small-12 columns">
            <p>
              <b>Capacity: </b><%= car.capacity %>
              <% if car.capacity > 1 %>
              people <% else %> person <% end %>
            </p>
            <p><b>Doors: </b><%= car.door %></p>
            <p>
              <b>Trunk: </b>
              <% if car.trunk == true %>
              Yes <% else %> No <% end %>
            </p>
          </div>
          <ul class="small-12 columns">
            <li class="left">
              <p><%= link_to 'Show', car %></p>
            </li>
            <% if user_signed_in? %>
            <li class="left">
              <p><%= link_to 'Rent', rent_path(car) %></p>
            </li>
            <li class="right">
              <p><%= link_to 'Edit', edit_car_path(car) %></p>
            </li>
            <li class="right">
              <p><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></p>
            </li>
            <% end %>
          </ul>
        </article>
      </li>
    <% end %>
  </ul>
  <br>
</section>

app/views/cars/new.html.erb
<h1 class="text-center">New car</h1>

<%= render 'form' %>

app/views/cars/rent.html.erb
<h1 class="text-center">Rent Car</h1>

<div class="row">
	<fieldset class="small-6 columns">
		<h2>User Information</h2>
		<div>
		  <strong>User Picture:</strong></br>
		  <%= image_tag current_user.avatar.url(:medium) %>
		</div>
		<p><strong>Full Name:</strong> <%= current_user.fullname %></p>
		<p><strong>Identification:</strong> <%= current_user.identification %></p>
		<p><strong>Address:</strong> <%= current_user.address %></p>
		<p><strong>Phone:</strong> <%= current_user.phone %></p>
		<p><strong>Cellphone:</strong> <%= current_user.cellphone %></p>
		<p><strong>Born date:</strong> <%= current_user.born_date %></p>
	</fieldset>

	<fieldset class="small-5 columns">
		<h2>Car Information</h2>
		<div>
		  <strong>Car Picture:</strong></br>
		  <%= image_tag @car.avatar.url(:medium) %>
		</div>
		<p><strong>Plate:</strong> <%= @car.plate %></p>
		<p><strong>Mileage:</strong> <%= @car.mileage %> <% if @car.mileage != nil %> km <% end %></p>
		<p><strong>Capacity:</strong> <%= @car.capacity %> 
			<% if @car.capacity > 1 %> people <% else %> person <% end %>
		</p>
		<p><strong>Brand:</strong> <%= @car.brand %></p>
		<p><strong>Year:</strong> <%= @car.year %></p>
		<p><strong>Color:</strong> <%= @car.color %></p>
		<p><strong>Motor:</strong> <%= @car.motor %></p>
		<p><strong>Description:</strong> <%= @car.description %></p>
		<p><strong>Gasoline:</strong> <%= @car.gasoline %> <% if @car.gasoline != nil %> lt <% end %></p>
		<p><strong>Transmision:</strong> 
			<% if @car.transmision == true %> Yes <% else %> No <% end %>
		</p>
		<p><strong>Trunk:</strong> <% if @car.trunk == true %> Yes <% else %> No <% end %></p>
		<p><strong>Doors:</strong> <%= @car.door %></p>
	</fieldset>
</div>

app/views/cars/show.html.erb
<div>
  <strong>Car Picture:</strong></br>
  <%= image_tag @car.avatar.url(:medium) %>
</div>

<p>
  <strong>Plate:</strong>
  <%= @car.plate %>
</p>

<p>
  <strong>Mileage:</strong>
  <%= @car.mileage %> <% if @car.mileage != nil %> km <% end %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @car.capacity %> <% if @car.capacity > 1 %> people <% else %> person <% end %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Motor:</strong>
  <%= @car.motor %>
</p>

<p>
  <strong>Description:</strong>
  <%= @car.description %>
</p>

<p>
  <strong>Gasoline:</strong>
  <%= @car.gasoline %> <% if @car.gasoline != nil %> lt <% end %>
</p>

<p>
  <strong>Transmision:</strong>
  <% if @car.transmision == true %> Yes <% else %> No <% end %>
</p>

<p>
  <strong>Trunk:</strong>
  <% if @car.trunk == true %> Yes <% else %> No <% end %>
</p>

<p>
  <strong>Doors:</strong>
  <%= @car.door %>
</p>

<%= link_to 'Edit', edit_car_path(@car), class: 'button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Car Rental" %></title>

	<%= stylesheet_link_tag	"application" %>
	<%= javascript_include_tag "vendor/modernizr" %>
	<%= csrf_meta_tags %>
</head>

<body>
	<header>
		<nav class="top-bar row" data-topbar>
			<ul class="title-area">
				<li class="name">
					<h1><%= link_to 'Car Rental', root_path %></h1>
				</li>
				<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
			</ul>

			<section class="top-bar-section">
			<!-- Right Nav Section -->
				<ul class="right">
					<% if user_signed_in? %>
					<li><%= image_tag current_user.avatar.url(:mini) %></li>
					<li><%= link_to current_user.fullname, edit_user_registration_path %></li>
					<li class="red"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'red' %></li>
					<% else %>
					<li><%= link_to 'Sign Up', new_user_registration_path, class: 'button-color' %></li>
					<li><%= link_to 'Sign In', new_user_session_path %></li>
					<% end %>
				</ul>

		<!-- Left Nav Section -->
				<ul class="left">
					<li><%= link_to 'Cars', cars_path, class: 'button-color' %></li>
				</ul>
			</section>
		</nav>
	</header>

	<section class="row">
		<div class="small-12 columns">
				<br>
				<% flash.each do |type, message| %>
						<div data-alert class="alert-box radius <%= flass_class type %>">
								<%= message %>
  							<a href="#" class="close">&times;</a>
						</div>
				<% end %>
				<%= yield %>
		</div>
	</section>

	<footer>
		<div class="wrapper">
			<div class="row">
				<ul class="legal small-6 medium-7 columns">
					<li><a href="#">Terms & Conditions</a></li>
					<li><a href="#">Privacy Policy</a></li>
					<li><a href="#">Help</a></li>
				</ul>

				<ul class="social-media small-6 medium-5 columns">
					<li class="right"><a id="youtube" href="#">Youtube</a></li>
					<li class="right"><a id="instagram" href="#">Instagram</a></li>
					<li class="right"><a id="twitter" href="#">Twitter</a></li>
					<li class="right"><a id="facebook" href="#">Facebook</a></li>
				</ul>
			</div>
		</div>
	</footer>


    <%= javascript_include_tag "application" %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br>
    <%= f.number_field :cellphone %>
  </div>
  <div class="field">
    <%= f.label :born_date %><br>
    <%= f.date_select :born_date %>
  </div>
  <div class="field">
    <%= f.label :identification %><br>
    <%= f.number_field :identification %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class: 'button' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Cellphone</th>
      <th>Born date</th>
      <th>Identification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= user.cellphone %></td>
        <td><%= user.born_date %></td>
        <td><%= user.identification %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div>
  <strong>Profile Picture:</strong>
  <%= image_tag @user.avatar.url(:thumb) %>
</div>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @user.identification %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @user.cellphone %>
</p>

<p>
  <strong>Born date:</strong>
  <%= @user.born_date %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: 'button' %>